
defaults:
  - config_vcs_flexible
  - override dataset: contrast_detection
  - override model: ean_space
  - override experiment: contrast_detection
  - _self_


train:
  epochs: 30

  loss:
    weights:
      unimodal_where_gain: 0.0

  noise_anneal:
    enabled: True
    warmup_epochs: 2 # how many 0.0 noise epochs there are
    anneal_epochs: 2 # how many epochs it takes to reach the max noise

  energy_anneal:
    enabled: True
    warmup_epochs: 4 # how many 0.0 energy epochs there are
    anneal_epochs: 2 # how many epochs it takes to reach the max energy

  lr_scheduler:
    enabled: False

  adam:
    lr: 0.0005

  skip_validation: True
  checkpoint_save_interval: 1
